routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/produto');
});


Route::resource('produto', 'ProdutoController');

Route::resource('categoria', 'CategoriaController');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $table = 'categorias';

    const created_at = 'tempo_criacao';
    const updated_at = 'tempo_alteracao';

    protected $primaryKey = 'CTG_ID';

    protected $fillable = [
        'CTG_NOME'
    ];
}

app/Produto.php
<?php

namespace App;

use App\Categoria;
use Illuminate\Database\Eloquent\Model;

class Produto extends Model
{
    protected $table = 'produtos';

    const created_at = 'tempo_criacao';
    const updated_at = 'tempo_alteracao';

    protected $primaryKey = 'PRO_ID';

    protected $fillable = [
        'PRO_NOME', 'PRO_IDCATEGORIA', 'PRO_DESCRICAO'
    ];

    public function categoria()
    {
        return $this->hasOne('App\Categoria', 'CTG_ID', 'PRO_IDCATEGORIA');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Categoria;
use Illuminate\Http\Request;
use App\Http\Requests\Categoria\CategoriaSaveRequest;
use App\Http\Requests\Categoria\CategoriaEditRequest;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::all();

        return view('categoria.listar', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categoria.criar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriaSaveRequest $request)
    {
        $dataForm = $request->all();

        Categoria::create($dataForm);

        return redirect('/categoria')->with('success', 'Categoria adicionado com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = Categoria::find($id);

        return view('categoria.editar', compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriaEditRequest $request, $id)
    {
        $dataForm = $request->all();

        $categoria = Categoria::find($id);

        $categoria->update($dataForm);

        return redirect('/categoria')->with('success', 'Categoria atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Categoria::destroy($id);

        return redirect('/categoria')->with('success', 'Categoria deletado com sucesso.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProdutoController.php
<?php

namespace App\Http\Controllers;

use App\Produto;
use App\Categoria;
use Illuminate\Http\Request;
use App\Http\Requests\Produto\ProdutoSaveRequest;
use App\Http\Requests\Produto\ProdutoEditRequest;

class ProdutoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produtos = Produto::all();

        return view('produto.listar', compact('produtos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = ['' => 'Selecione Categoria'];
        $_categorias = Categoria::all();
        foreach($_categorias as $categoria){
          $categorias[$categoria->CTG_ID] = $categoria->CTG_NOME;
        }

        return view('produto.criar', compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProdutoSaveRequest $request)
    {
        $dataForm = $request->all();

    		Produto::create($dataForm);

        return redirect('/produto')->with('success', 'Produto adicionado com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $produto = Produto::find($id);

        $categorias = ['' => 'Selecione Categoria'];
        $_categorias = Categoria::all();
        foreach($_categorias as $categoria){
          $categorias[$categoria->CTG_ID] = $categoria->CTG_NOME;
        }

        return view('produto.editar', compact('produto', 'categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProdutoEditRequest $request, $id)
    {
        $dataForm = $request->all();

        $produto = Produto::find($id);

        $produto->update($dataForm);

        return redirect('/produto')->with('success', 'Produto atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Produto::destroy($id);

      return redirect('/produto')->with('success', 'Produto deletado com sucesso.');
    }
}

resources/views/categoria/criar.blade.php
@extends('layouts.app')

@section('title', 'Adicionar Categoria')

@section('categoria', 'active')

@section('content')

{!! Form::open(['route' => 'categoria.store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Adicionar Categoria</h3>
    </div>

    <div class="col-md-8">
        <div class='form-group'>
            {{ Form::label('CTG_NOME', 'Nome:', ['data-error' => $errors->first('CTG_NOME')]) }}
            {{ Form::text('CTG_NOME', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

            @if ($errors->has('CTG_NOME'))
            <span class="help-block">
                <strong style="color: red;">{{ $errors->first('CTG_NOME') }}</strong>
            </span>
            @endif
        </div>
    </div>

    <div class="col-md-4">
        <button type="submit" type="button" class="btn btn-block btn-success"><i class="fa fa-floppy-o"></i> Salvar cadastro</button>
        <button onclick="history.back()" type="button" class="btn btn-block btn-danger"><i class="fa fa-close"></i> Cancelar</button>
    </div>

</div>
{!! Form::close() !!}

@stop

resources/views/categoria/editar.blade.php
@extends('layouts.app')

@section('title', 'Atualizar Categoria')

@section('categoria', 'active')

@section('content')

{!! Form::model($categoria, ['route' => ['categoria.update', $categoria->CTG_ID], 'method' => 'PUT', 'enctype' => 'multipart/form-data']) !!}
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Atualizar Categoria</h3>
    </div>

    <div class="col-md-8">
        <div class='form-group'>
            {{ Form::label('CTG_NOME', 'Nome:', ['data-error' => $errors->first('CTG_NOME')]) }}
            {{ Form::text('CTG_NOME', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

            @if ($errors->has('CTG_NOME'))
            <span class="help-block">
                <strong style="color: red;">{{ $errors->first('CTG_NOME') }}</strong>
            </span>
            @endif
        </div>
    </div>

    <div class="col-md-4">
        <button type="submit" type="button" class="btn btn-block btn-warning"><i class="fa fa-pencil"></i> Atualizar cadastro</button>
        <button onclick="history.back()" type="button" class="btn btn-block btn-danger"><i class="fa fa-close"></i> Cancelar</button>
    </div>

</div>
{!! Form::close() !!}

@stop

resources/views/categoria/listar.blade.php
@extends('layouts.app')

@section('title', 'Listar Categorias')

@section('categoria', 'active')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Listar Categorias</h3>
        <p><a href="{{ route('categoria.create') }}" class="btn btn-primary">Novo</a></p>

        <table id="table" class="table table-responsive table-bordered table-hover powertabela">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categorias as $ctg)
                <tr>
                    <td>{{ $ctg->CTG_ID  }}</td>
                    <td>{{ $ctg->CTG_NOME }}</td>
                    <td>

                        <?php // Botão editar ?>
                        <div class="btn-group">
                            <a href="{{ route('categoria.edit', ['ctg' => $ctg->CTG_ID]) }}" type="button" class="btn btn-warning btn-flat"><i class="fa fa-pencil"></i></a>
                        </div>

                        <?php // Botão deletar?>
                        <div class="btn-group">
                            <?php $deleteForm = "delete-form-{$loop->index}"; ?>
                            <a class="btn btn-danger btn-flat" data-toggle="modal" data-target="#delete_ctg_ID{{$ctg->CTG_ID}}"><i class="fa fa-trash-o"></i></a>

                            <?php// modal deletar ?>
                            <div class="modal fade" id="delete_ctg_ID{{$ctg->CTG_ID }}" tabindex="-1" role="dialog" aria-labelledby="delete_ctg_ID{{$ctg->CTG_ID}}Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title text-primary" id="delete_ctg_ID{{$ctg->CTG_ID}}Label"><i class="fa fa-trash-o"></i> Deletar Categoria</h4>
                                        </div>
                                        <div class="modal-body">

                                            <p class="alert alert-danger">Tem certeza que deseja excluir categoria "{{ $ctg->CTG_NOME }}" ?</p>
                                            <div class="form-actions">
                                                <a href="{{ route('categoria.destroy', ['ctg' => $ctg->CTG_ID]) }}" onclick="event.preventDefault(); document.getElementById('{{$deleteForm}}').submit();" class="btn btn-danger btn-flat">SIM</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">NÃO</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            {!! Form::open(['route' => ['categoria.destroy', 'ctg' => $ctg->CTG_ID], 'method' => 'DELETE', 'id' => $deleteForm, 'style' => 'display:none']) !!}
                            {!! Form::close() !!}

                        </div>

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>
@stop

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="_token" content="{{csrf_token()}}" />
        <title>@yield('title')</title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/dist/css/bootstrap.min.css') }}">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/font-awesome.min.css') }}">
        <!-- Ionicons -->
        <link rel="stylesheet" href="{{ asset('vendor/Ionicons/css/ionicons.min.css') }}">

        <!-- Chosen -->
        <link rel="stylesheet" href="{{ asset('vendor/chosen/chosen.css') }}">

        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">

        <link rel="stylesheet" href="//cdn.datatables.net/v/bs/dt-1.10.18/datatables.min.css">

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Gugi" rel="stylesheet">
    </head>

    <body>

      <div class="container">

          <ul class="nav nav-tabs">
              <li role="presentation" class="@yield('produto')"><a href="/produto">Produtos</a></li>
              <li role="presentation" class="@yield('categoria')" ><a href="/categoria">Categorias</a></li>
          </ul>

          @if(session()->has('success'))
          <div style="padding-top: 30px">
              <div class="alert alert-success">
                  {{ session()->get('success') }}
              </div>
          </div>
          @endif

          @yield('content')
      </div>

      <script src="{{ asset('vendor/jquery/dist/jquery.min.js') }}"></script>
      <script src="{{ asset('vendor/jquery/dist/jquery.slimscroll.min.js') }}"></script>
      <script src="{{ asset('vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>

      <script src="{{ asset('js/jquery-inputmask/dist/jquery.inputmask.bundle.js') }}"></script>

      <!-- Chosen -->
      <script src="{{ asset('vendor/adminlte/vendor/chosen/chosen.jquery.js') }}"></script>

      <!-- Select2 -->
      <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

      <!-- DataTables with bootstrap 3 renderer -->
      <script src="//cdn.datatables.net/v/bs/dt-1.10.18/datatables.min.js"></script>

      <!-- ChartJS -->
      <script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js"></script>

      <script type="text/javascript">
        $(document).ready( function () {
          $('#table').DataTable();
        } );
      </script>

    </body>
</html>

resources/views/produto/criar.blade.php
@extends('layouts.app')

@section('title', 'Adicionar Produto')

@section('produto', 'active')

@section('content')

{!! Form::open(['route' => 'produto.store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Adicionar Produto</h3>
    </div>

    <div class="col-md-8">
        <div class='row'>

            <div class='col-md-6'>

                <?php // Nome ?>
                <div class='form-group'>
                    {{ Form::label('PRO_NOME', 'Nome:', ['data-error' => $errors->first('PRO_NOME')]) }}
                    {{ Form::text('PRO_NOME', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

                    @if ($errors->has('PRO_NOME'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_NOME') }}</strong>
                    </span>
                    @endif
                </div>

                <?php // Descrição ?>
                <div class='form-group'>
                    {{ Form::label('PRO_DESCRICAO', 'Descrição:', ['data-error' => $errors->first('PRO_DESCRICAO')]) }}
                    {{ Form::text('PRO_DESCRICAO', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

                    @if ($errors->has('PRO_DESCRICAO'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_DESCRICAO') }}</strong>
                    </span>
                    @endif
                </div>

            </div>

            <div class="col-md-6">
                <?php // Categoria ?>
                <div class='form-group'>
                    {{ Form::label('PRO_IDCATEGORIA', 'Categoria:', ['data-error' => $errors->first('PRO_CATEGORIA')]) }}
                    {{ Form::select('PRO_IDCATEGORIA', $categorias, null, ['class' => 'avalidate form-control chosen-select-UNI_IDIMOVEL', 'autocomplete' => 'off']) }}



                    @if ($errors->has('PRO_IDCATEGORIA'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_IDCATEGORIA') }}</strong>
                    </span>
                    @endif
                </div>
            </div>

        </div>
    </div>

    <div class="col-md-4">
        <button type="submit" type="button" class="btn btn-block btn-success"><i class="fa fa-floppy-o"></i> Salvar cadastro</button>
        <button onclick="history.back()" type="button" class="btn btn-block btn-danger"><i class="fa fa-close"></i> Cancelar</button>
    </div>

</div>
{!! Form::close() !!}

@stop

resources/views/produto/editar.blade.php
@extends('layouts.app')

@section('title', 'Atualizar Produto')

@section('produto', 'active')

@section('content')

{!! Form::model($produto, ['route' => ['produto.update', $produto->PRO_ID], 'method' => 'PUT', 'enctype' => 'multipart/form-data']) !!}
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Atualizar Produto</h3>
    </div>

    <div class="col-md-8">
        <div class='row'>

            <div class='col-md-6'>

                <?php // Nome ?>
                <div class='form-group'>
                    {{ Form::label('PRO_NOME', 'Nome:', ['data-error' => $errors->first('PRO_NOME')]) }}
                    {{ Form::text('PRO_NOME', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

                    @if ($errors->has('PRO_NOME'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_NOME') }}</strong>
                    </span>
                    @endif
                </div>

                <?php // Descrição ?>
                <div class='form-group'>
                    {{ Form::label('PRO_DESCRICAO', 'Descrição:', ['data-error' => $errors->first('PRO_DESCRICAO')]) }}
                    {{ Form::text('PRO_DESCRICAO', null, ['class' => 'avalidate form-control', 'autocomplete' => 'off']) }}

                    @if ($errors->has('PRO_DESCRICAO'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_DESCRICAO') }}</strong>
                    </span>
                    @endif
                </div>

            </div>

            <div class="col-md-6">
                <?php // Categoria ?>
                <div class='form-group'>
                    {{ Form::label('PRO_IDCATEGORIA', 'Categoria:', ['data-error' => $errors->first('PRO_CATEGORIA')]) }}
                    {{ Form::select('PRO_IDCATEGORIA', $categorias, null, ['class' => 'avalidate form-control chosen-select-UNI_IDIMOVEL', 'autocomplete' => 'off']) }}



                    @if ($errors->has('PRO_IDCATEGORIA'))
                    <span class="help-block">
                        <strong style="color: red;">{{ $errors->first('PRO_IDCATEGORIA') }}</strong>
                    </span>
                    @endif
                </div>
            </div>

        </div>
    </div>

    <div class="col-md-4">
        <button type="submit" type="button" class="btn btn-block btn-warning"><i class="fa fa-pencil"></i> Atualizar cadastro</button>
        <button onclick="history.back()" type="button" class="btn btn-block btn-danger"><i class="fa fa-close"></i> Cancelar</button>
    </div>

</div>
{!! Form::close() !!}

@stop

resources/views/produto/listar.blade.php
@extends('layouts.app')

@section('title', 'Listar Produtos')

@section('produto', 'active')

@section('content')
<div class="row">
    <div class="col-md-12">
        <h3 class="text-primary">Listar Produtos</h3>
        <p><a href="{{ route('produto.create') }}" class="btn btn-primary">Novo</a></p>

        <table id="table" class="table table-responsive table-bordered table-hover powertabela">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Categoria</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($produtos as $pro)
                <tr>
                    <td>{{ $pro->PRO_ID  }}</td>
                    <td>{{ $pro->PRO_NOME }}</td>
                    <td>{{ $pro->categoria->CTG_NOME }}</td>
                    <td>{{ $pro->PRO_DESCRICAO }}</td>
                    <td>

                        <?php // Botão editar ?>
                        <div class="btn-group">
                            <a href="{{ route('produto.edit', ['pro' => $pro->PRO_ID]) }}" type="button" class="btn btn-warning btn-flat"><i class="fa fa-pencil"></i></a>
                        </div>

                        <?php // Botão deletar?>
                        <div class="btn-group">
                            <?php $deleteForm = "delete-form-{$loop->index}"; ?>
                            <a class="btn btn-danger btn-flat" data-toggle="modal" data-target="#delete_pro_ID{{$pro->PRO_ID}}"><i class="fa fa-trash-o"></i></a>

                            <?php// modal deletar ?>
                            <div class="modal fade" id="delete_pro_ID{{$pro->PRO_ID }}" tabindex="-1" role="dialog" aria-labelledby="delete_pro_ID{{$pro->PRO_ID}}Label" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            <h4 class="modal-title text-primary" id="delete_pro_ID{{$pro->PRO_ID}}Label"><i class="fa fa-trash-o"></i> Deletar Produto</h4>
                                        </div>
                                        <div class="modal-body">

                                            <p class="alert alert-danger">Tem certeza que deseja excluir produto "{{ $pro->PRO_NOME }}" ?</p>
                                            <div class="form-actions">
                                                <a href="{{ route('produto.destroy', ['pro' => $pro->PRO_ID]) }}" onclick="event.preventDefault(); document.getElementById('{{$deleteForm}}').submit();" class="btn btn-danger btn-flat">SIM</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">NÃO</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                            {!! Form::open(['route' => ['produto.destroy', 'pro' => $pro->PRO_ID], 'method' => 'DELETE', 'id' => $deleteForm, 'style' => 'display:none']) !!}
                            {!! Form::close() !!}

                        </div>

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

    </div>
</div>
@stop